### ISSUE TITLE
JS💩 

### ISSUE THREAD

**Issue by odduck41** [Katarni/dnd-battels#1]
JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩 JS💩

**Comment by Katarni** [comment]
еще раз такое, и я пожалуюсь
